#!/usr/bin/python
# -*- coding: utf-8 -*-
#whois.py
import sys
import socket

"""
whois.arin.net (US IP addrs)
whois.apnic.net (Asia Specific IP Addrs)
whois.ripe.net (European IP Addrs)
whois.lacnic.net (Latin America/Carribean IP addrs)
rs.internic.net (*.COM,*.NET,*.ORG,*.EDU)
whois.nic.uk (*.AC)
whois.nic.ad (*.AD)
whois.uaenic.ae (*.AE)
whois.nic.ag (*.AG)
whois.offshore.com.ai (*.AI)
whois.inima.al (*.AL)
whois.una.net (*.AN)
whois.fccn.pt (*.AO)
whois.nsrc.org (*.AQ)
whois.nic.ar (*.AR)
whois.nic.as (*.AS)
whois.amnic.net (*.AM,*.AU,*.AT)
whois.domain.az (*.AZ)
whois.utic.net.ba (*.BA)
whois.domains.org.bb (*.BB)
whois.dns.be (*.BE)
whois.onatel.bf (*.BF)
whois.digsys.bg (*.BG)
whois.batelco.com.bh (*.BH)
whois.nic.bi (*.BI)
whois.nic.biz (*.BIZ)
whois.bermudanic.bm (*.BM)
whois.brunet.bn (*.BN)
whois.digsys.bo (*.BO)
whois.unibel.by (*.BY)
whois.belizenic.bz (*.BZ)
whois.registro.fapesp.br (*.BR)
whois.nic.bt (*.BT)
whois.norid.no (*.BV)
whois.cira.ca (*.CA)
whois.nic.cc (*.CC)
whois.nic.cd (*.CD)
whois.socatel.intnet.cf (*.CF)
whois.nic.cg (*.CG)
whois.nic.ch (*.CH)
whois.aipdi.ci (*.CI)
whois.oyster.net.ck (*.CK)
whois.nic.cl (*.CL)
whois.info.intelcam.cm (*.CM)
whois.cnnic.net.cn (*.CN)
whois.nic.uniandes.edu.co (*.CO)
whois.nic.coop (*.COOP)
whois.nic.cu (*.CU)
whois.nic.cx (*.CX)
whois.nic.cy (*.CY)
whois.nic.cz (*.CZ)
whois.denic.de (*.DE)
whois.dk-hostmaster.dk (*.DK)
whois.intnet.dj (*.DJ)
whois.nic.do (*.DO)
whois.nic.dz (*.DZ)
whois.nic.ec (*.EC)
whois.educause.net (*.EDU)
whois.eenet.ee (*.EE)
whois.frcu.eun.eg (*.EG)
whois.nic.es (*.ES)
whois.telecom.net.et (*.ET)
whois.ripe.net (*.FI)
whois.usp.ac.fj (*.FJ)
whois.fidc.org.fk (*.FK)
whois.dot.fm (*.FM)
whois.nic.fo (*.FO)
whois.nic.fr (*.FR)
whois.nic.uk (*.GB)
whois.nic.net.ge (*.GE)
whois.nplus.gf (*.GF)
whois.nic.gg (*.GG)
whois.ghana.com (*.GH)
whois.gibnet.gi (*.GI)
whois.nic.gl (*.GL)
whois.nic.gm (*.GM)
whois.psg.com (*.GN)
whois.nic.gov (*.GOV)
whois.nic.gp (*.GP)
whois.getesa.gq (*.GQ)
whois.hostmaster.gr (*.GR)
whois.adamsnames.tc (*.GS)
whois.uvg.edu.gt (*.GT)
whois.gadao.gov.gu (*.GU)
whois.hkdnr.net.hk (*.HK)
whois.registry.hm (*.HM)
whois.nic.hn (*.HN)
whois.carnet.hr (*.HR)
whois.nic.hu (*.HU)
whois.idnet.net.id (*.ID)
whois.domainregistry.ie (*.IE)
whois.isoc.org.il (*.IL)
whois.nic.im (*.IM)
whois.domain.ncst.ernet.in (*.IN)
whois.afilias.com (*.INFO)
whois.iana.org (*.INT)
whois.nic.io (*.IO)
whois.nic.ir (*.IR)
whois.isnic.is (*.IS)
whois.nic.it (*.IT)
whois.isles.net (*.JE)
whois.nic.net.jo (*.JO)
whois.nic.ad.jp (*.JP)
whois.nbnet.co.ke (*.KE)
whois.domain.kg (*.KG)
whois.mptc.gov.kh (*.KH)
whois.clu.edu (*.KN)
whois.nic.or.kr (*.KR)
whois.domainname.net.kw (*.KW)
whois.domain.kz (*.KZ)
whois.aub.edu.lb (*.LB)
whois.isisworld.lc (*.LC)
whois.nic.li (*.LI)
whois.nic.lk (*.LK)
whois.psg.com (*.LR)
whois.co.ls (*.LS)
whois.domreg.lt (*.LT)
whois.dns.lu (*.LU)
whois.nic.lv (*.LV)
whois.nic.ly (*.LY)
whois.iam.ma (*.MA)
whois.nic.mc (*.MC)
whois.ripe.net (*.MD)
whois.nic.mil (*.MIL)
whois.orstom.mg (*.MG)
whois.nic.net.mh (*.MH)
whois.mpt.com.mk (*.MK)
whois.nic.mm (*.MM)
whois.nic.mn (*.MN)
whois.umac.mo (*.MO)
whois.marketplace.mp (*.MP)
whois.nic.mq (*.MQ)
whois.univ-mkc.mr (*.MR)
whois.adamsnames.tc (*.MS)
whois.um.edu.mt (*.MT)
whois.posix.co.za (*.MU)
whois.tarsus.net (*.MW)
whois.nic.mx (*.MX)
whois.mynic.net.my (*.MY)
whois.nambu.uem.mz (*.MZ)
na-nic.com.na (*.NA)
whois.nic.name (*.NAME)
whois.norstom.nc (*.NC)
whois.names.nf (*.NF)
whois.nic.ni (*.NI)
whois.domain-registry.nl (*.NL)
whois.norid.no (*.NO)
whois.mos.com.np (*.NP)
whois.nic.nu (*.NU)
whois.domainz.net.nz (*.NZ)
whois.gto.net.om (*.OM)
whois.nic.pa (*.PA)
whois.ekeko.rcp.net.pe (*.PE)
whois.domreg.org.ph (*.PH)
whois.unitech.ac.pg (*.PG)
whois.pknic.net.pk (*.PK)
whois.nask.pl (*.PL)
whois.nic.pm (*.PM)
whois.nic.pn (*.PN)
whois.uprr.pr (*.PR)
whois.nic.ps (*.PS)
whois.fccn.pt (*.PT)
whois.nic.py (*.PY)
whois.qatar.net.qa (*.QA)
whois.nic.fr (*.RE)
whois.rnc.ro (*.RO)
whois.ripn.net (*.RU)
whois.nic.rw (*.RW)
whois.saudinic.net.sa (*.SA)
whois.sbnic.net.sb (*.SB)
whois.sudatel.sd (*.SD)
whois.nic-se.se (*.SE)
whois.nic.net.sg (*.SG)
whois.nic.sh (*.SH)
whois.arnes.si (*.SI)
whois.norid.no (*.SJ)
whois.sk-nic.sk (*.SK)
whois.intelcom.sm (*.SM)
whois.nic.sn (*.SN)
whois.nic.so (*.SO)
whois.st-registry.tecnisys.net (*.ST)
whois.ripn.net (*.SU)
whois.svnet.org.sv (*.SV)
whois.syriatel.net (*.SY)
whois.iafrica.sz (*.SZ)
whois.adamsnames.tc (*.TC)
whois.tit.td (*.TD)
whois.adamsnames.tc (*.TF)
whois.nic.tg (*.TG)
whois.thnic.net (*.TH)
whois.nic.tj (*.TJ)
whois.nic.tm (*.TM)
whois.ati.tn (*.TN)
whois.tonic.to (*.TO)
whois.nic.tp (*.TP)
whois.metu.edu.tr (*.TR)
whois.nic.tt (*.TT)
whois.twnic.net (*.TW)
whois.psg.com (*.TZ)
whois.networksolutions.com (*.TV)
nic.net.ua (*.UA)
whois.nic.ug (*.UG)
whois.nic.uk (*.UK)
whois.ja.net (*.UK)
whois.ripe.net (*.UK)
whois.isi.edu (*.UM)
whois.nic.us (*.US)
whois.rau.edu.uy (*.UY)
whois.freenet.uz (*.UZ)
whois.nic.ve (*.VE)
whois.nic.fr (*.WF)
whois.adamsnames.tc (*.VG)
whois.nic.vi (*.VI)
whois.batin.com.vn (*.VN)
whois.vunic.vu (*.VU)
samoanic.ws (*.WS)
whois.nic.fr (*.YT)
whois.nic.yu (*.YU)
whois.co.za (*.ZA)
whois.zamnet.zm (*.ZM)
"""

def whois(domain):
    suffix = domain.split('.')[-1]
    dict_whois_server={
                 'com':'whois.internic.net',
                 'net':'whois.internic.net',
                 'edu':'whois.internic.net',
                 'org':'whois.publicinterestregistry.net',
                 'cn':'whois.cnnic.net.cn',
                 'cc':'ccwhois.verisign-grs.com',
                 'tv':'tvwhois.verisign-grs.com',
                 #'jobs':'jobswhois.verisign-grs.com',
                 'info':'whois.afilias.net',
                 'biz':'whois.neulevel.biz',
                 'name':'whois.nic.name',
                 'jobs':'whois.encirca.com',
                 }

    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        whois_server=dict_whois_server.get(suffix)
        print "Use",whois_server
        s.connect((whois_server,43))      
        s.send(domain + "\r\n")
        response = ''
        while True:
            data = s.recv(4096)
            response += data
            if data == '':
                break
        s.close()
        return response
    except Exception,E:
        print E    
  
if __name__ == "__main__":
    #print whois("sina.com.cn")
    #print whois("creativecommons.org")
    #print whois("moko.cc")
    #print whois("tsinghua.edu.cn")
    #print whois("yale.edu")
    #print whois("lvye.info")
    #print whois("google.biz")
    #print whois("moko.cc")
    print whois("pps.tv")
    #print whois("goto.jobs")
    #print whois("mystock.name")
    #print whois("sina.com.cn")
    